### PR TITLE
CrossOver19

### PR DESCRIPTION
**Pull request by Gcenx**

### CODE REVIEW

**Comment by Gcenx** [comment]
@qparis you would need to manually force this it seems

**Comment by qparis** [comment]
Hmm no, this branch as unreslved conflicts

**Comment by Gcenx** [comment]
The other way to avoid this issue as it’s a false positive for WineCX, would be making a new empty branch then committing CrossOver19 then adding my updated patches. Then marking a release for winecx-19.0.0

**Comment by qparis** [comment]
I think your branch can be comitted directly to master yep

**Pull request closed without merging**
